from . import (
    achievements,
    achievements_of_users,
    authors,
    bookmarks,
    books,
    books_of_user,
    friendships,
    genres,
    notifications,
    summarized_books_of_user,
    tests_of_user,
    text_of_book,
    users,
)
